---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=1.4
  - ANSIBLE_VERSION=1.5
  - ANSIBLE_VERSION=1.6
  - ANSIBLE_VERSION=1.7

before_install:
  - sudo apt-get update -qq

  # Install dnsutils (for nslookup)
  - sudo apt-get install dnsutils

install:
  # Install Ansible.
  - pip install ansible==$ANSIBLE_VERSION

  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo -vvvv"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test (primary) dns server
  - >
    nslookup 127.0.0.1
    | grep 'Server'
    | awk '{print $2}'
    | grep -q '8.8.8.8'
    && (echo 'Configuration test: pass' && exit 0)
    || (echo 'Configuration test: fail' && exit 1)

notifications:
  email: false
