---
# tasks file for dns
- name: remove resolvconf
  apt:
    name: resolvconf
    state: absent
  when: dns_remove_resolvconf
  tags: [configuration, dns, dns-remove-resolvconf]

- name: configure dns servers - /etc/resolv.conf
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
  tags: [configuration, dns, dns-configure-resolvconf]

- name: get dhclient file stats
  stat:
    path: "{{ dns_dhclient_file }}"
  register: dhclient_file_stats
  tags: [configuration, dns, dns-dhclient-file-stats]

- name: check dhclient file stats
  fail:
    msg: "dhclient file not found"
  when: dhclient_file_stats.stat.exists == False
  tags: [configuration, dns, dns-dhclient-file-stats]

- name: configure dns servers - dhclient file
  lineinfile:
    regexp: '^(.*)(supersede|prepend) {{ item.name }} (.*);$'
    backrefs: yes
    line: '\1{{ dns_dhclient_rule }} {{ item.name }} {{ item.value }};'
    dest: "{{ dns_dhclient_file }}"
    state: present
  with_items:
    - name: 'domain-name'
      value: '\"{{ dns_domain }}\"'
    - name: 'domain-name-servers'
      value: '{% for dns_nameserver in dns_nameservers %}{{ dns_nameserver }}{% if not loop.last %}, {% endif %}{% endfor %}'
    - name: 'domain-search'
      value: '{% for dns_search in dns_searches %}\"{{ dns_search }}\"{% if not loop.last %}, {% endif %}{% endfor %}'
  when: item.value != ''
  tags: [configuration, dns, dns-configure-dhclient-file]
